name: CDK Deploy

on:
  push:
    branches:
      - production
      - development
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      DATABASE_URL: ${{vars.DATABASE_URL}}
      DATABASE_USER: ${{ vars.DATABASE_USER }}
      DATABASE: ${{ vars.DATABASE }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      BCRYPT_SALT: ${{ vars.BCRYPT_SALT }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      REGION: ${{ vars.REGION }}
      ACCOUNT: ${{ vars.ACCOUNT }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REDIRECT_URI: ${{ vars.GOOGLE_REDIRECT_URI }}
      AUTH_REDIRECT_URL: ${{ vars.AUTH_REDIRECT_URL }}
      IMAGES_BUCKET: ${{ vars.IMAGES_BUCKET }}
      NODE_ENV: ${{ github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Install build
        run: yarn build

      - name: Install AWS CDK
        run: yarn global add aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.REGION}}

      - name: Deploy CDK Stack
        run: cdk deploy --require-approval never
        env:
          AWS_ACCOUNT_ID: ${{ vars.ACCOUNT }}
          AWS_REGION: ${{ vars.REGION }}
